source 'https://rubygems.org'
gem "github-pages", "~> 214", group: :jekyll_plugins
group :jekyll_plugins do
    gem "jemoji", "~> 0.12.0"
    gem "jekyll-feed", "~> 0.15.1"
end
platforms :mingw, :x64_mingw, :mswin, :jruby do
    gem "tzinfo", "~> 1.2"
    gem "tzinfo-data"
end